ARDUINO_DIR = /opt/arduino
ARDMK_DIR = ~/dev/Arduino-Makefile
AVR_TOOLS_DIR = /usr/include
BOARD_TAG = teensy35
USER_LIB_PATH += ./lib/
ARDUINO_LIBS = ros_lib RoboClaw Encoder
include $(ARDMK_DIR)/Teensy.mk
