#!/usr/bin/env python
# Kawin Nikomborirak
# Supposed to display a transformed image from the camera, using the
# recognize_road function.
# For some reason very laggy

import rospy
from cv_bridge import CvBridge, CvBridgeError
import cv2
from sensor_msgs.msg import Image


class road_recognition:
    def __init__(self):
        self.image = rospy.Subscriber(
            '/camera/image_raw', Image, self.callback, queue_size=10)
        self.bridge = CvBridge()

    def recognize_road(img):
        return img

    def callback(self, data):
        try:
            cv_image = self.bridge.imgmsg_to_cv2(data, 'mono8')
        except CvBridgeError as e:
            print(e)
        cv2.imshow('Image window', cv_image)
        cv2.waitKey()


def main():
    road_recognition()
    rospy.init_node('road_recognition', anonymous=True)
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print('Shutting down')


if __name__ == '__main__':
    main()
